name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    env:
      GITHUB_TOKEN: '${{ github.token }}'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn all

  build-ubuntu-20-04:
    env:
      GITHUB_TOKEN: '${{ github.token }}'
      ACTION_BUILDCACHE_TAG: "v0.27.6"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn all

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          cache_key: build-test-${{ matrix.os }}

  test-ubuntu-20-04:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          cache_key: build-test-${{ matrix.os }}
          buildcache_tag: v0.27.6